/**
 * Turning generated bytes into a saved file.
 *
 * Object URLs are revoked immediately after the click, so a blob holding a
 * whole class's names is not left alive for the lifetime of the tab.
 *
 * File names never contain a student name. They carry the class and the date,
 * which is what a teacher needs to find the file again.
 */

export function safeFileName(parts: {
  kind: string;
  classNumber?: string | undefined;
  date?: string | undefined;
  extension: string;
}): string {
  const date = (parts.date ?? new Date().toISOString().slice(0, 10)).replace(/-/g, '');
  const klass = (parts.classNumber ?? '').replace(/[^0-9가-힣-]/g, '');
  const middle = klass ? `_${klass}` : '';
  return `${parts.kind}${middle}_${date}.${parts.extension}`;
}

export function downloadBlob(blob: Blob, fileName: string): void {
  const url = URL.createObjectURL(blob);
  try {
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = fileName;
    anchor.rel = 'noopener';
    document.body.appendChild(anchor);
    anchor.click();
    anchor.remove();
  } finally {
    // A short delay lets the browser start the download before the URL dies.
    setTimeout(() => URL.revokeObjectURL(url), 2000);
  }
}

export function downloadText(text: string, fileName: string, mime = 'application/json'): void {
  downloadBlob(new Blob([text], { type: `${mime};charset=utf-8` }), fileName);
}

export function downloadBytes(bytes: ArrayBuffer, fileName: string, mime: string): void {
  downloadBlob(new Blob([bytes], { type: mime }), fileName);
}
